spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/oauth2
#    username: tonmoyjdbc
#    password: tonmoy
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
